---
title: "Companion Notebook Grading"
author: "Adam Gilbert"
format: html
theme: flatly
---

## Notebook Grading Resources

I've developed a few resources useful for grading students on these notebooks. You should be able to copy all of the files to your own Google Drive and use them for your classes. There are three files in this [Google Drive Folder](https://drive.google.com/drive/folders/1zj2yvJyRFgXmwaqWGkUkbIRXTwj3Jpip?usp=sharing), described as follows:

+ `Hash Code Submission Form` -- a Google Form for collecting student hash codes generated at the end of each notebook. 
+ `Hash Code Submission Form (Responses)` -- a Google Sheet collecting responses from the form above.
+ `grading_script.r` -- an R Script to automatically consume student hash codes from the Google Sheet above and build an `overall_grades` data frame, containing one row per student and calculated grades using weightings supplied by the user. Lines 5 - 29 provide instructions for using the grading script.

:::{.callout-important}
## Non-Hash Code Submission

If any student submits something other than their hash code into the *hash code* section of the Google Form, the grading script will crash. You'll need to identify the student and delete their response from the collection spreadsheet for the script to run.
:::
