<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.43">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="MAT241 Class">

<title>Practice Problems Notebook</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="PracticeInferenceProblems_Complete_files/libs/clipboard/clipboard.min.js"></script>
<script src="PracticeInferenceProblems_Complete_files/libs/quarto-html/quarto.js"></script>
<script src="PracticeInferenceProblems_Complete_files/libs/quarto-html/popper.min.js"></script>
<script src="PracticeInferenceProblems_Complete_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="PracticeInferenceProblems_Complete_files/libs/quarto-html/anchor.min.js"></script>
<link href="PracticeInferenceProblems_Complete_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="PracticeInferenceProblems_Complete_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="PracticeInferenceProblems_Complete_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="PracticeInferenceProblems_Complete_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="PracticeInferenceProblems_Complete_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="PracticeInferenceProblems_Complete_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="PracticeInferenceProblems_Complete_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction-to-inference-mom-week-5-hw" id="toc-introduction-to-inference-mom-week-5-hw" class="nav-link active" data-scroll-target="#introduction-to-inference-mom-week-5-hw">Introduction to Inference (MoM Week 5 HW)</a>
  <ul class="collapse">
  <li><a href="#problem-1-solved" id="toc-problem-1-solved" class="nav-link" data-scroll-target="#problem-1-solved">Problem 1 Solved</a></li>
  <li><a href="#problem-2-solved" id="toc-problem-2-solved" class="nav-link" data-scroll-target="#problem-2-solved">Problem 2 Solved</a></li>
  <li><a href="#problem-5-unsolved" id="toc-problem-5-unsolved" class="nav-link" data-scroll-target="#problem-5-unsolved">Problem 5 Unsolved</a></li>
  <li><a href="#problem-6-unsolved" id="toc-problem-6-unsolved" class="nav-link" data-scroll-target="#problem-6-unsolved">Problem 6 Unsolved</a></li>
  <li><a href="#problem-11-unsolved" id="toc-problem-11-unsolved" class="nav-link" data-scroll-target="#problem-11-unsolved">Problem 11 Unsolved</a></li>
  </ul></li>
  <li><a href="#inference-on-one-and-two-proportions-mom-week-6-hw" id="toc-inference-on-one-and-two-proportions-mom-week-6-hw" class="nav-link" data-scroll-target="#inference-on-one-and-two-proportions-mom-week-6-hw">Inference on One and Two Proportions (MoM Week 6 HW)</a>
  <ul class="collapse">
  <li><a href="#problem-1-unsolved" id="toc-problem-1-unsolved" class="nav-link" data-scroll-target="#problem-1-unsolved">Problem 1 Unsolved</a></li>
  <li><a href="#problem-3-solved" id="toc-problem-3-solved" class="nav-link" data-scroll-target="#problem-3-solved">Problem 3 Solved</a></li>
  <li><a href="#problem-4-unsolved" id="toc-problem-4-unsolved" class="nav-link" data-scroll-target="#problem-4-unsolved">Problem 4 Unsolved</a></li>
  <li><a href="#problem-5-solved" id="toc-problem-5-solved" class="nav-link" data-scroll-target="#problem-5-solved">Problem 5 Solved</a></li>
  </ul></li>
  <li><a href="#chi-square-goodness-of-fit-and-independence-multiple-proportions" id="toc-chi-square-goodness-of-fit-and-independence-multiple-proportions" class="nav-link" data-scroll-target="#chi-square-goodness-of-fit-and-independence-multiple-proportions">Chi-Square Goodness of Fit and Independence (Multiple Proportions)</a>
  <ul class="collapse">
  <li><a href="#problem-1-solved-1" id="toc-problem-1-solved-1" class="nav-link" data-scroll-target="#problem-1-solved-1">Problem 1 Solved</a></li>
  <li><a href="#problem-2-solved-1" id="toc-problem-2-solved-1" class="nav-link" data-scroll-target="#problem-2-solved-1">Problem 2 Solved</a></li>
  <li><a href="#problem-3-unsolved" id="toc-problem-3-unsolved" class="nav-link" data-scroll-target="#problem-3-unsolved">Problem 3 Unsolved</a></li>
  <li><a href="#problem-4-solved" id="toc-problem-4-solved" class="nav-link" data-scroll-target="#problem-4-solved">Problem 4 Solved</a></li>
  </ul></li>
  <li><a href="#inference-on-one-and-two-means" id="toc-inference-on-one-and-two-means" class="nav-link" data-scroll-target="#inference-on-one-and-two-means">Inference on One and Two Means</a>
  <ul class="collapse">
  <li><a href="#problem-1-solved-2" id="toc-problem-1-solved-2" class="nav-link" data-scroll-target="#problem-1-solved-2">Problem 1 Solved</a></li>
  <li><a href="#problem-2-solved-2" id="toc-problem-2-solved-2" class="nav-link" data-scroll-target="#problem-2-solved-2">Problem 2 Solved</a></li>
  <li><a href="#problem-3-unsolved-1" id="toc-problem-3-unsolved-1" class="nav-link" data-scroll-target="#problem-3-unsolved-1">Problem 3 Unsolved</a></li>
  <li><a href="#problem-4-unsolved-1" id="toc-problem-4-unsolved-1" class="nav-link" data-scroll-target="#problem-4-unsolved-1">Problem 4 Unsolved</a></li>
  </ul></li>
  <li><a href="#sample-size-problems" id="toc-sample-size-problems" class="nav-link" data-scroll-target="#sample-size-problems">Sample Size Problems</a>
  <ul class="collapse">
  <li><a href="#problem-1-solved-3" id="toc-problem-1-solved-3" class="nav-link" data-scroll-target="#problem-1-solved-3">Problem 1 Solved</a></li>
  <li><a href="#problem-2-solved-3" id="toc-problem-2-solved-3" class="nav-link" data-scroll-target="#problem-2-solved-3">Problem 2 Solved</a></li>
  </ul></li>
  <li><a href="#comparing-many-means-with-analysis-of-variance-anova" id="toc-comparing-many-means-with-analysis-of-variance-anova" class="nav-link" data-scroll-target="#comparing-many-means-with-analysis-of-variance-anova">Comparing Many Means with Analysis of Variance (ANOVA)</a>
  <ul class="collapse">
  <li><a href="#problem-1-solved-4" id="toc-problem-1-solved-4" class="nav-link" data-scroll-target="#problem-1-solved-4">Problem 1 Solved</a></li>
  <li><a href="#problem-2-solved-4" id="toc-problem-2-solved-4" class="nav-link" data-scroll-target="#problem-2-solved-4">Problem 2 Solved</a></li>
  <li><a href="#problem-3-unsolved-2" id="toc-problem-3-unsolved-2" class="nav-link" data-scroll-target="#problem-3-unsolved-2">Problem 3 Unsolved</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="PracticeInferenceProblems_Complete.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Practice Problems Notebook</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>MAT241 Class </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<p>In this notebook, we’ll work through several practice problems from our Textbook and MyOpenMath.</p>
<section id="introduction-to-inference-mom-week-5-hw" class="level2">
<h2 class="anchored" data-anchor-id="introduction-to-inference-mom-week-5-hw">Introduction to Inference (MoM Week 5 HW)</h2>
<section id="problem-1-solved" class="level3">
<h3 class="anchored" data-anchor-id="problem-1-solved">Problem 1 Solved</h3>
<p><strong>Problem 1:</strong> For each of the following situations, state whether the parameter of interest is a mean or a proportion. It may be helpful to examine whether individual responses are numerical or categorical.</p>
<ul>
<li>In a survey, one hundred college students are asked how many hours per week they spend on the Internet.</li>
</ul>
<blockquote class="blockquote">
<ul>
<li>Participants are being asked: “How many hours per week do you spend on the internet?”</li>
<li>Sample Answer: 5 hours, 6 and a half hours…numerical values.</li>
<li>So this study is investigating a <em>population mean</em> (the average number of hours per week on the internet).</li>
</ul>
</blockquote>
<ul>
<li>In a survey, one hundred college students are asked: “What percentage of the time you spend on the Internet is part of your course work?”</li>
</ul>
<blockquote class="blockquote">
<ul>
<li>Participants are asked: “What percentage of the time you spend on the Internet is part of your course work?”</li>
<li>Sample Answer: 75%, 43%</li>
<li>Investigating <em>average</em> percentage of time spent.</li>
</ul>
</blockquote>
<ul>
<li>In a survey, one hundred college students are asked whether or not they cited information from Wikipedia in their papers.</li>
</ul>
<blockquote class="blockquote">
<ul>
<li>Participants asked: “Have you cited Wikipedia on a paper?”</li>
<li>Sample answer: Yes, No</li>
<li>This is a study on <em>proportions</em></li>
</ul>
</blockquote>
<ul>
<li>In a survey, one hundred college students are asked what percentage of their total weekly spending is on alcoholic beverages.</li>
</ul>
<blockquote class="blockquote">
<ul>
<li>Participants asked: “What percentage of your weekly spending is on alcohol?”</li>
<li>Sample Answer: 12%, 5%, numeric percentages</li>
<li>This is a study on <em>means</em> (the average percentage of total weekly spending)</li>
</ul>
</blockquote>
<ul>
<li>In a sample of one hundred recent college graduates, it is found that 85 percent expect to get a job within one year of their graduation date.</li>
</ul>
<blockquote class="blockquote">
<ul>
<li>Participants asked: “Do you expect to find a job within one year of graduating?”</li>
<li>Sample Answer: yes/no</li>
<li>This is a study on <em>proportions</em> (the proportion of recent college graduates who expect to find a job within one year of graduating).</li>
</ul>
</blockquote>
</section>
<section id="problem-2-solved" class="level3">
<h3 class="anchored" data-anchor-id="problem-2-solved">Problem 2 Solved</h3>
<p><strong>Problem 2:</strong> A poll conducted in 2013 found that 52% of U.S. adult Twitter users get at least some news on Twitter, and the standard error for this estimate was 2.4%. Conduct a hypothesis test at the <span class="math inline">\(\alpha = 0.05\)</span> level of significance to determine whether a majority of US adult Twitter users get at least some news on Twitter.</p>
<blockquote class="blockquote">
<p><em>Solution.</em></p>
<ul>
<li><strong>Hypotheses:</strong> <span class="math inline">\(\begin{array}{ll} H_0: &amp; \mu = 0.5\\ H_a: &amp; \mu &gt; 0.5\end{array}\)</span></li>
<li><strong>Picture of Alternative Hypothesis:</strong></li>
</ul>
</blockquote>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PracticeInferenceProblems_Complete_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<ul>
<li><strong>Set <span class="math inline">\(\alpha\)</span> Level:</strong> Notice that <span class="math inline">\(\alpha = 0.05\)</span> in the problem statement.</li>
<li><strong>Compute the Test Statistic:</strong></li>
</ul>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Here is a code cell</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>null_value <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>point_estimate <span class="ot">&lt;-</span> <span class="fl">0.52</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>st_error <span class="ot">&lt;-</span> <span class="fl">0.024</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>test_stat <span class="ot">&lt;-</span> (point_estimate <span class="sc">-</span> null_value)<span class="sc">/</span>st_error</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>test_stat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8333333</code></pre>
</div>
</div>
<blockquote class="blockquote">
<ul>
<li><strong>Compute the <span class="math inline">\(p\)</span>-value:</strong> Notice that our <span class="math inline">\(p\)</span>-value is the area to the right of our test statistic. We use the picture of the alternative hypothesis to tell this.</li>
</ul>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>p_val <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(test_stat, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>p_val</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2023284</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PracticeInferenceProblems_Complete_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<ul>
<li><strong>Compare the <span class="math inline">\(p\)</span>-value to the Level of Significance:</strong> Since our <span class="math inline">\(p\)</span>-value exceeds the level of significance, our sample is not one of those “unlikely” samples which are favorable to the alternative hypothesis. That is, our sample is <em>compatible</em> with a world in which the null hypothesis is true – we do <strong>not</strong> have significant evidence to suggest that more than 50% of US Adult Twitter users get some news from Twitter. <span class="math inline">\(_\blacktriangledown\)</span></li>
</ul>
</blockquote>
</section>
<section id="problem-5-unsolved" class="level3">
<h3 class="anchored" data-anchor-id="problem-5-unsolved">Problem 5 Unsolved</h3>
<p><strong>Problem 5:</strong> A store randomly samples 603 shoppers over the course of a year and finds that 142 of them made their visit because of a coupon they’d received in the mail. Construct a 95% confidence interval for the fraction of all shoppers during the year whose visit was because of a coupon they’d received in the mail.</p>
</section>
<section id="problem-6-unsolved" class="level3">
<h3 class="anchored" data-anchor-id="problem-6-unsolved">Problem 6 Unsolved</h3>
<p><strong>Problem 6:</strong> A tutoring company would like to understand if most students tend to improve their grades (or not) after they use their services. They sample 200 of the students who used their service in the past year and ask them if their grades have improved or declined from the previous year. Of the 200 sampled, 185 said that their grades had improved. Determine whether the data provides evidence to suggest that the companies tutoring services suggest that over 90% of customers report improved grades after using the tutoring services. Use the <span class="math inline">\(\alpha = 0.1\)</span> level of significance.</p>
</section>
<section id="problem-11-unsolved" class="level3">
<h3 class="anchored" data-anchor-id="problem-11-unsolved">Problem 11 Unsolved</h3>
<p><strong>Problem 11:</strong> A poll conducted in 2013 found that 52% of U.S. adult Twitter users get at least some news on Twitter (Pew, 2013). The standard error for this estimate was 2.4%, and a normal distribution may be used to model the sample proportion. Construct a 99% confidence interval for the fraction of U.S. adult Twitter users who get some news on Twitter, and interpret the confidence interval in context.</p>
</section>
</section>
<section id="inference-on-one-and-two-proportions-mom-week-6-hw" class="level2">
<h2 class="anchored" data-anchor-id="inference-on-one-and-two-proportions-mom-week-6-hw">Inference on One and Two Proportions (MoM Week 6 HW)</h2>
<section id="problem-1-unsolved" class="level3">
<h3 class="anchored" data-anchor-id="problem-1-unsolved">Problem 1 Unsolved</h3>
<p><strong>Problem 1:</strong> About 77% of young adults think they can achieve the American dream. Determine if the following statements are true or false, and explain your reasoning.</p>
<ul>
<li><p>The distribution of sample proportions of young Americans who think they can achieve the American dream in samples of size 20 is left skewed.</p></li>
<li><p>The distribution of sample proportions of young Americans who think they can achieve the American dream in random samples of size 40 is approximately normal since <span class="math inline">\(n \geq 30\)</span>.</p></li>
<li><p>A random sample of 60 young Americans where 85% think they can achieve the American dream would be considered unusual.</p></li>
<li><p>A random sample of 120 young Americans where 85% think they can achieve the American dream would be considered unusual.</p></li>
</ul>
</section>
<section id="problem-3-solved" class="level3">
<h3 class="anchored" data-anchor-id="problem-3-solved">Problem 3 Solved</h3>
<p><strong>Problem 3:</strong> Among a simple random sample of 331 American adults who do not have a four-year college degree and are not currently enrolled in school, 48% said they decided not to go to college because they could not afford school. Calculate a 90% confidence interval for the proportion of Americans who decide to not go to college because they cannot afford it, and interpret the interval in context.</p>
<blockquote class="blockquote">
<p><em>Solution.</em> In this problem, we are asked to construct a confidence interval, with 90% confidence. We’ll follow the steps to do so below.</p>
<p>We are trying to capture a single population proportion here. The formula for a confidence interval is <span class="math inline">\(\left(\text{point estimate}\right) \pm \left(\text{critical value}\right)\left(S_E\right)\)</span>.</p>
<ul>
<li><strong>Point Estimate:</strong> The point estimate is the sample proportion. Here, that is 48%.</li>
<li><strong>Standard Error (<span class="math inline">\(S_E\)</span>):</strong> Using the standard error decision tree, we find that <span class="math inline">\(\displaystyle{S_E = \sqrt{\frac{p\left(1 - p\right)}{n}}}\)</span>. Notice also that there is no information about <em>degrees of freedom</em> (<span class="math inline">\(df\)</span>) in this box, so we are free to use the normal distribution with this problem.</li>
<li><strong>Critical Value:</strong> Since we are working with a normal distribution, we can use the small table at the top of the standard error decision tree to determine that the critical value is <span class="math inline">\(z_{\alpha/2} = 1.65\)</span>.</li>
</ul>
<p>Since we have all of the components of the confidence interval fomula, we are now ready to construct our interval.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>point_estimate <span class="ot">&lt;-</span> <span class="fl">0.48</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>st_error <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fl">0.48</span><span class="sc">*</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.48</span>)<span class="sc">/</span><span class="dv">331</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>critical_value <span class="ot">&lt;-</span> <span class="fl">1.65</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>lower <span class="ot">&lt;-</span> point_estimate <span class="sc">-</span> (critical_value<span class="sc">*</span>st_error)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>upper <span class="ot">&lt;-</span> point_estimate <span class="sc">+</span> (critical_value<span class="sc">*</span>st_error)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(lower, upper)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4346902 0.5253098</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Interpretation:</strong> Given the results above, we are 90% confident that, of American Adults who chose not to go to college, the proportion making that decision because they could not afford to is between 43.47% and 52.53%. Note that we <strong>cannot</strong> claim that a majority or minority of American Adults made this decision for this reason since our confidence interval contains proportions both below and above 50%. <span class="math inline">\(_\blacktriangledown\)</span></p>
</blockquote>
</section>
<section id="problem-4-unsolved" class="level3">
<h3 class="anchored" data-anchor-id="problem-4-unsolved">Problem 4 Unsolved</h3>
<p><strong>Problem 4:</strong> A 2010 Pew Research foundation poll indicates that among 1,099 college graduates, 33% watch The Daily Show. Meanwhile, 22% of the 1,110 people with a high school degree but no college degree in the poll watch The Daily Show. Construct a 95% confidence interval for <span class="math inline">\(\left(p_{\text{college grad}} - p_{\text{HS or less}}\right)\)</span>, where p is the proportion of those who watch The Daily Show</p>
</section>
<section id="problem-5-solved" class="level3">
<h3 class="anchored" data-anchor-id="problem-5-solved">Problem 5 Solved</h3>
<p><strong>Problem 5:</strong> Researchers studying the link between prenatal vitamin use and autism surveyed the mothers of a random sample of children aged 24 - 60 months with autism and conducted another separate random sample for children with typical development. The table below shows the number of mothers in each group who did and did not use prenatal vitamins during the three months before pregnancy (periconceptional period). Conduct a hypotheses to test for independence of use of prenatal vitamins during the three months before pregnancy and autism. (Schmidt, 2011)</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(\hspace{1cm}\)</span></th>
<th>Autism</th>
<th>Typical Development</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>No vitamin</td>
<td>111</td>
<td>70</td>
<td>181</td>
</tr>
<tr class="even">
<td>Vitamin</td>
<td>143</td>
<td>159</td>
<td>302</td>
</tr>
<tr class="odd">
<td>Total</td>
<td>254</td>
<td>229</td>
<td>483</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><em>Solution.</em> Note that we are conducting a hypothesis test here for a difference of two population <em>proportions</em>. The first population is <em>mothers and children where the mother took a prenatal vitamin during pregnancy</em>, and the second population is <em>mothers and children who did not take a prenatal vitamin during pregnancy</em>.</p>
<ul>
<li><strong>Hypotheses:</strong> The hypotheses are <span class="math inline">\(\begin{array}{ll} H_0: &amp; p_{\text{vitamin}} = p_{\text{no vitamin}}\\ H_a: &amp; p_{\text{vitamin}} \neq p_{\text{no vitamin}}\end{array}\)</span>. While this framing of the hypotheses is fine, it hides (i) the null value and (ii) the population parameter from us. It is generally better to rewrite these hypotheses so that we have “zero on one side”. That is, the hypotheses are <span class="math inline">\(\begin{array}{ll} H_0: &amp; p_{\text{vitamin}} - p_{\text{no vitamin}} = 0\\ H_a: &amp; p_{\text{vitamin}} - p_{\text{no vitamin}} \neq 0\end{array}\)</span></li>
<li><strong>Picture of Alternative Hypothesis:</strong></li>
</ul>
</blockquote>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PracticeInferenceProblems_Complete_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<ul>
<li><strong>Set <span class="math inline">\(\alpha\)</span> Level:</strong> Notice that we’ll assume <span class="math inline">\(\alpha = 0.05\)</span> since we aren’t told otherwise. Note that this <span class="math inline">\(\alpha\)</span> is split up across the two tails, so each shaded area in the image above represents 2.5% of samples.</li>
<li><strong>Compute the Test Statistic:</strong></li>
</ul>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>null_value <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>p_vitamin <span class="ot">&lt;-</span> <span class="dv">143</span><span class="sc">/</span><span class="dv">302</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>p_no_vitamin <span class="ot">&lt;-</span> <span class="dv">111</span><span class="sc">/</span><span class="dv">181</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>point_estimate <span class="ot">&lt;-</span> p_vitamin <span class="sc">-</span> p_no_vitamin</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Compute Standard Error</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>term1 <span class="ot">&lt;-</span> p_vitamin<span class="sc">*</span>(<span class="dv">1</span> <span class="sc">-</span> p_vitamin)<span class="sc">/</span><span class="dv">302</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>term2 <span class="ot">&lt;-</span> p_no_vitamin<span class="sc">*</span>(<span class="dv">1</span> <span class="sc">-</span> p_no_vitamin)<span class="sc">/</span><span class="dv">181</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>st_error <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(term1 <span class="sc">+</span> term2)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>test_stat <span class="ot">&lt;-</span> (point_estimate <span class="sc">-</span> null_value)<span class="sc">/</span>st_error</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>test_stat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -3.023898</code></pre>
</div>
</div>
<blockquote class="blockquote">
<ul>
<li><strong>Compute the <span class="math inline">\(p\)</span>-value:</strong> Notice that our <span class="math inline">\(p\)</span>-value needs to account for samples whose difference in proportions is less than 0 and also samples whose difference in proportions is greater than 0. Our <span class="math inline">\(p\)</span>-value will need to include two areas, according to our picture of the alternative hypotheses! Because of this, we’ll calculate the area in one tail of the distribution and then double it.</li>
</ul>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>tail_area <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(test_stat, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>p_val <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">*</span>tail_area</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>p_val</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.002495405</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PracticeInferenceProblems_Complete_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<ul>
<li><strong>Compare the <span class="math inline">\(p\)</span>-value to the Level of Significance:</strong> Since our <span class="math inline">\(p\)</span>-value is less than the level of significance, our sample is one of those “unlikely” samples which are favorable to the alternative hypothesis. That is, our sample is <em>incompatible</em> with a world in which the null hypothesis is true – we <strong>do</strong> have significant evidence to suggest that there is an association between prenatal vitamin use and the development of autism in children. <span class="math inline">\(_\blacktriangledown\)</span></li>
</ul>
</blockquote>
<blockquote class="blockquote">
<blockquote class="blockquote">
<p><em>Note.</em> We have not tested whether the use of the particular prenatal vitamin increases or decreases the risk of development with autism here.</p>
</blockquote>
</blockquote>
</section>
</section>
<section id="chi-square-goodness-of-fit-and-independence-multiple-proportions" class="level2">
<h2 class="anchored" data-anchor-id="chi-square-goodness-of-fit-and-independence-multiple-proportions">Chi-Square Goodness of Fit and Independence (Multiple Proportions)</h2>
<section id="problem-1-solved-1" class="level3">
<h3 class="anchored" data-anchor-id="problem-1-solved-1">Problem 1 Solved</h3>
<p><strong>Problem 1 (Open Source Textbook):</strong> A professor using an open source introductory statistics book predicts that 20% of the students will purchase a hard copy of the book, 5% will print it out from the web, and 75% will read it online. At the end of the semester he asks his students to complete a survey where they indicate what format of the book they used. Of the 126 students, 19 said they bought a hard copy of the book, 9 said they printed it out from the web, and 98 said they read it online. Conduct a test to determine whether the professor’s predictions were inaccurate.</p>
<blockquote class="blockquote">
<p><em>Solution.</em> Note that we are conducting a hypothesis test here to determine whether the sample data provide evidence <em>against</em> the instructor’s predicted distribution. We are working with proportions here, since the question being asked of the students is “<em>how did you access the textbook?</em>”. This is a grouping question. Additionally, we have more than two groups here for which we are comparing proportions. According to the Standard Error Decision Tree, this puts us into the <span class="math inline">\(\chi^2\)</span> box.</p>
<p>This box tells us that we’ll be using the <span class="math inline">\(\chi^2\)</span> distribution and test statistic, rather than the normal distribution and typical test statistic formula. From the <code>Topic 14</code> notebook, you’ll remember that the <span class="math inline">\(\chi^2\)</span> test statistic is computed as <span class="math inline">\(\displaystyle{\chi^2_{\text{test stat}} = \sum_{\text{Groups}}{\frac{\left(\text{observed} - \text{expected}\right)^2}{\text{expected}}}}\)</span>. Let’s see how this all plays out below.</p>
<ul>
<li><strong>Hypotheses:</strong> The hypotheses are <span class="math inline">\(\begin{array}{ll} H_0: &amp; \text{The instructor's assumed distribution is correct}\\ H_a: &amp; \text{The distribution is different}\end{array}\)</span></li>
<li><strong>Picture of Alternative Hypothesis:</strong></li>
</ul>
</blockquote>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PracticeInferenceProblems_Complete_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<ul>
<li><strong>Set <span class="math inline">\(\alpha\)</span> Level:</strong> Notice that we’ll assume <span class="math inline">\(\alpha = 0.05\)</span> since we aren’t told otherwise. With the <span class="math inline">\(\chi^2\)</span> distribution, our <span class="math inline">\(p\)</span>-values will always be in the upper tail (the right side of the distribution).</li>
<li><strong>Compute the Test Statistic:</strong> In order to compute the test statistic, we’ll need to compare our observed (sample) counts to our expected counts (assuming the distribution from the null hypothesis). We’ll first compute the expected counts in each category below.</li>
</ul>
</blockquote>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Purchased</th>
<th>Printed</th>
<th>Read Online</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Observed</strong></td>
<td>19</td>
<td>9</td>
<td>98</td>
</tr>
<tr class="even">
<td><strong>Expected</strong></td>
<td><span class="math inline">\(126\left(0.20\right) = 25.2\)</span></td>
<td><span class="math inline">\(126\left(0.05\right) = 6.3\)</span></td>
<td><span class="math inline">\(126\left(0.75\right) = 94.5\)</span></td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>From here, we’re ready to compute the <span class="math inline">\(\chi^2\)</span> test statistic.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>observed <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">19</span>, <span class="dv">9</span>, <span class="dv">98</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>expected <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">25.2</span>, <span class="fl">6.3</span>, <span class="fl">94.5</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>test_stat <span class="ot">&lt;-</span> <span class="fu">sum</span>((observed <span class="sc">-</span> expected)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>expected)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>test_stat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.812169</code></pre>
</div>
</div>
<blockquote class="blockquote">
<ul>
<li><strong>Compute the <span class="math inline">\(p\)</span>-value:</strong> We’ll now convert our test statistic (a boundary value) into a <span class="math inline">\(p\)</span>-value. Notice from our picture of the alternative hypothesis that our <span class="math inline">\(p\)</span>-value will be the area to the right of the test statistic. Additionally, remember that we’re working with the <span class="math inline">\(\chi^2\)</span> distribution and not the normal distribution here – we’ll use <code>pchisq()</code> rather than <code>pnorm()</code>. The <span class="math inline">\(\chi^2\)</span> distribution is determined by a number of degrees of freedom, not a mean or standard deviation – for this particular type of test (<em>goodness of fit</em>) – the degrees of freedom is one less than the number of groups.</li>
</ul>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>p_val <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(test_stat, <span class="at">df =</span> <span class="dv">3</span> <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>p_val</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2451011</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PracticeInferenceProblems_Complete_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<ul>
<li><strong>Compare the <span class="math inline">\(p\)</span>-value to the Level of Significance:</strong> The <span class="math inline">\(p\)</span>-value for our test is around 0.2451. This means that, if the null hypothesis is true, the probability of observing a sample at least as favorable to the alternative hypothesis as ours is around 24.51%. This is relatively likely!</li>
</ul>
<p>Our <span class="math inline">\(p\)</span> value exceeds the level of significance, so our sample is <strong>not</strong> one of those “unlikely” samples which are favorable to the alternative hypothesis. That is, our sample is <em>compatible</em> with a world in which the null hypothesis is true – we <strong>do not</strong> have significant evidence to suggest that the instructors expected distribution was incorrect. <span class="math inline">\(_\blacktriangledown\)</span></p>
</blockquote>
</section>
<section id="problem-2-solved-1" class="level3">
<h3 class="anchored" data-anchor-id="problem-2-solved-1">Problem 2 Solved</h3>
<p><strong>Problem 2 (Barking Deer):</strong> Microhabitat factors associated with forage and bed sites of barking deer in Hainan Island, China were examined. In this region woods make up 4.8% of the land, cultivated grass plot makes up 14.7%, and deciduous forests make up 39.6%. Of the 426 sites where the deer forage, 4 were categorized as woods, 16 as cultivated grassplot, and 61 as deciduous forests. The table below summarizes these data.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Woods</th>
<th>Cultivated Grassplot</th>
<th>Deciduous Forests</th>
<th>Other</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>4</td>
<td>16</td>
<td>61</td>
<td>345</td>
<td>426</td>
</tr>
</tbody>
</table>
<p>Conduct a test to determine whether barking deer prefer to forage in certain habitats over others.</p>
<blockquote class="blockquote">
<p><em>Solution.</em> We’re asked to test a hypothesis here. We’ll test whether the barking deer have no habitat preference (that is, they distributed randomly amongst the four habitat categories). Under the null hypothesis, we’ll assume that the deer have no environmental preference, and so they are observed proportionally to each group. That is, 4.8% of deer are observed in <em>woods</em>, 14.7% of deer are observed in <em>cultivated grasslands</em>, 39.6% of deer are observed in <em>deciduous forests</em>, and 40.1% of deer are observed in <em>other</em> environments.</p>
<p>Notice that we are conducting a hypothesis test here, since we are asked to “conduct a test”. We’re working with a proportion since the participants are deer, and each one is asked a grouping question (“where do you like to forage/bed?”). For these reasons, we are working with a <span class="math inline">\(\chi^2\)</span> test – in particular, we are working through a <span class="math inline">\(\chi\)</span>-squared test for <em>goodness of fit</em>.</p>
<p>The test statistic for a <span class="math inline">\(\chi^2\)</span> test is computed as <span class="math inline">\(\displaystyle{\chi^2 = \sum_{\text{groups}}{\frac{\left(\text{obsrrved} - \text{expected}\right)^2}{\text{expected}}}}\)</span></p>
<p>If we assumed that deer had no habitat preference, then we should observe them proportional to each of the coverages. That is, we would have expected to observe <span class="math inline">\(426\cdot\left(0.048\right)\approx 20.448\)</span> deer in <em>woods</em>, <span class="math inline">\(426\cdot\left(0.147\right) = 62.622\)</span> deer on <em>cultivated grasslands</em>, <span class="math inline">\(426\left(0.396\right) = 168.696\)</span> deer in <em>deciduous forest</em>, and <span class="math inline">\(426\left(0.409\right) = 174.234\)</span> deer in <em>other</em> habitats.</p>
</blockquote>
<blockquote class="blockquote">
<ul>
<li><strong>Hypotheses:</strong> The hypotheses are <span class="math inline">\(\begin{array}{ll} H_0: &amp; \text{The deer have no habitat preference.}\\ H_a: &amp; \text{The deer do have a habitat preference.}\end{array}\)</span></li>
<li><strong>Picture of Alternative Hypothesis:</strong></li>
</ul>
</blockquote>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PracticeInferenceProblems_Complete_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<ul>
<li><strong>Set <span class="math inline">\(\alpha\)</span> Level:</strong> Notice that we’ll assume <span class="math inline">\(\alpha = 0.05\)</span> since we aren’t told otherwise. With the <span class="math inline">\(\chi^2\)</span> distribution, our <span class="math inline">\(p\)</span>-values will always be in the upper tail (the right side of the distribution).</li>
<li><strong>Compute the Test Statistic:</strong> In order to compute the test statistic, we’ll need to compare our observed (sample) counts to our expected counts (assuming the distribution from the null hypothesis). From our earlier discussion, we have the following observed and expected counts.</li>
</ul>
</blockquote>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Woods</th>
<th>Cultivated Grassplot</th>
<th>Deciduous Forests</th>
<th>Other</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Observed</strong></td>
<td>4</td>
<td>16</td>
<td>61</td>
<td>345</td>
<td>426</td>
</tr>
<tr class="even">
<td><strong>Expected</strong></td>
<td>20.488</td>
<td>62.622</td>
<td>168.696</td>
<td>174.234</td>
<td><span class="math inline">\(\approx\)</span> 426</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>From here, we’re ready to compute the <span class="math inline">\(\chi^2\)</span> test statistic.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>observed <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">16</span>, <span class="dv">61</span>, <span class="dv">345</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>expected <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">20.488</span>, <span class="fl">62.622</span>, <span class="fl">168.696</span>, <span class="fl">174.234</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>test_stat <span class="ot">&lt;-</span> <span class="fu">sum</span>((observed <span class="sc">-</span> expected)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>expected)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>test_stat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 284.0994</code></pre>
</div>
</div>
<blockquote class="blockquote">
<ul>
<li><strong>Compute the <span class="math inline">\(p\)</span>-value:</strong> We’ll now convert our test statistic (a boundary value) into a <span class="math inline">\(p\)</span>-value. Notice from our picture of the alternative hypothesis that our <span class="math inline">\(p\)</span>-value will be the area to the right of the test statistic. Additionally, remember that we’re working with the <span class="math inline">\(\chi^2\)</span> distribution and not the normal distribution here – we’ll use <code>pchisq()</code> rather than <code>pnorm()</code>. The <span class="math inline">\(\chi^2\)</span> distribution is determined by a number of degrees of freedom, not a mean or standard deviation – for this particular type of test (<em>goodness of fit</em>) – the degrees of freedom is one less than the number of groups. We have four groups here, so three degrees of freedom.</li>
</ul>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>p_val <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(test_stat, <span class="at">df =</span> <span class="dv">4</span> <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>p_val</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Scale for x is already present.
Adding another scale for x, which will replace the existing scale.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 4583 rows containing missing values or values outside the scale range
(`geom_line()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 94 rows containing missing values or values outside the scale range
(`geom_ribbon()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PracticeInferenceProblems_Complete_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<ul>
<li><strong>Compare the <span class="math inline">\(p\)</span>-value to the Level of Significance:</strong> The <span class="math inline">\(p\)</span>-value for our test is extremely small – it is being rounded to <span class="math inline">\(0\)</span>. This means that, if the null hypothesis is true, the probability of observing a sample at least as favorable to the alternative hypothesis as ours is not likely at all!</li>
</ul>
<p>Our <span class="math inline">\(p\)</span> value falls below level of significance, so our sample <strong>is</strong> one of those “unlikely” samples which are favorable to the alternative hypothesis. That is, our sample is <em>incompatible</em> with a world in which the null hypothesis is true – we <strong>do</strong> have significant evidence to suggest that the barking deer have habitat preferences. <span class="math inline">\(_\blacktriangledown\)</span></p>
</blockquote>
</section>
<section id="problem-3-unsolved" class="level3">
<h3 class="anchored" data-anchor-id="problem-3-unsolved">Problem 3 Unsolved</h3>
<p><strong>Problem 3 (Full-Body Scan):</strong> The table below summarizes a data set we first encountered in Exercise 6.26 regarding views on full-body scans and political affiliation. The differences in each political group may be due to chance. Conduct a test to determine whether an individual’s party affiliation and their support of full-body scans are independent of one another. It may be useful to first add on an extra column for row totals before proceeding with the computations.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Republican</th>
<th>Democrat</th>
<th>Independent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Should</td>
<td>264</td>
<td>299</td>
<td>351</td>
</tr>
<tr class="even">
<td>Should Not</td>
<td>38</td>
<td>55</td>
<td>77</td>
</tr>
<tr class="odd">
<td>Don’t Know / No Answer</td>
<td>16</td>
<td>15</td>
<td>22</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td>318</td>
<td>369</td>
<td>450</td>
</tr>
</tbody>
</table>
</section>
<section id="problem-4-solved" class="level3">
<h3 class="anchored" data-anchor-id="problem-4-solved">Problem 4 Solved</h3>
<p><strong>Problem 4 (Offshore Drilling):</strong> The table below summarizes a data set we first encountered in Exercise 6.23 that examines the responses of a random sample of college graduates and non-graduates on the topic of oil drilling. Complete a chi-square test for these data to check whether there is a statistically significant difference in responses from college graduates and non-graduates.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>College Grad</th>
<th>Not College Grad</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Support Offshore Drilling</td>
<td>154</td>
<td>132</td>
</tr>
<tr class="even">
<td>Oppose Offshore Drilling</td>
<td>180</td>
<td>126</td>
</tr>
<tr class="odd">
<td>Do not know</td>
<td>104</td>
<td>131</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td>438</td>
<td>389</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><em>Solution.</em> Note that we are conducting a hypothesis test here to determine whether education level (college grad or not) and stance on offshore oil drilling (support, oppose, or unsure) are independent. Again, we are working with proportions here, since the questions being asked of the participants are “<em>do you have a college degree?</em>” and “<em>are you in favor of offshore oil drilling?</em>”. These are grouping questions. Additionally, we have more than two groups here for which we are comparing proportions (we’ll have six – for each of the two levels of education, there are three stances on drilling). According to the Standard Error Decision Tree, this puts us into the <span class="math inline">\(\chi^2\)</span> box.</p>
<p>As with the other problems in this section, this box tells us that we’ll be using the <span class="math inline">\(\chi^2\)</span> distribution and test statistic, rather than the normal distribution and typical test statistic formula. From the <code>Topic 14</code> notebook, you’ll remember that the <span class="math inline">\(\chi^2\)</span> test statistic is computed as <span class="math inline">\(\displaystyle{\chi^2_{\text{test stat}} = \sum_{\text{Groups}}{\frac{\left(\text{observed} - \text{expected}\right)^2}{\text{expected}}}}\)</span>. Let’s see how this all plays out below.</p>
<ul>
<li><strong>Hypotheses:</strong> The hypotheses are <span class="math display">\[\begin{array}{ll} H_0: &amp; \text{Education level and stance on offshore oil drilling are independent}\\ H_a: &amp; \text{Education level and stance on offshore oil drilling are dependent (associated)}\end{array}\]</span></li>
<li><strong>Picture of Alternative Hypothesis:</strong></li>
</ul>
</blockquote>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PracticeInferenceProblems_Complete_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<ul>
<li><strong>Set <span class="math inline">\(\alpha\)</span> Level:</strong> Notice that we’ll assume <span class="math inline">\(\alpha = 0.05\)</span> since we aren’t told otherwise. With the <span class="math inline">\(\chi^2\)</span> distribution, our <span class="math inline">\(p\)</span>-values will always be in the upper tail (the right side of the distribution).</li>
<li><strong>Compute the Test Statistic:</strong> In order to compute the test statistic, we’ll need to compare our observed (sample) counts to our expected counts (assuming that education and stance on drilling are independent).</li>
</ul>
<p>In order to proceed, we’ll need to estimate the probabilities associated with each of the categories (college grad, non-grad, support drilling, oppose drilling, and unsure). Notice that there are <span class="math inline">\(438 + 389 = 827\)</span> total participants in this study. From here, we can see the following:</p>
<ul>
<li><span class="math inline">\(438/827 \approx 0.5296\)</span> are college grads.</li>
<li><span class="math inline">\(389/827 \approx 0.4704\)</span> are not college grads.</li>
<li><span class="math inline">\(\left(154 + 132\right)/827 \approx 0.3458\)</span> support drilling.</li>
<li><span class="math inline">\(\left(180 + 126\right)/827 \approx 0.37\)</span> oppose drilling.</li>
<li><span class="math inline">\(\left(104 + 131\right)/827 \approx 0.2842\)</span> are unsure of their support.</li>
</ul>
<p>Now that we have those estimated group membership probabilities, we’ll compute our expected counts by assuming that education level and stance on drilling are independent. Recall that if two events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are independent, then <span class="math inline">\(\mathbb{P}\left[A \text{ and } B\right] = \mathbb{P}\left[A\right]\cdot\mathbb{P}\left[B\right]\)</span>.</p>
</blockquote>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>College Grad</th>
<th>Not College Grad</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Support Offshore Drilling</td>
<td><span class="math inline">\(827\left(0.5296\right)\left(0.3458\right) \approx 151.45\)</span></td>
<td><span class="math inline">\(827\left(0.4704\right)\left(0.3458\right) \approx 134.52\)</span></td>
</tr>
<tr class="even">
<td>Oppose Offshore Drilling</td>
<td><span class="math inline">\(827\left(0.5296\right)\left(0.37\right) \approx 162.05\)</span></td>
<td><span class="math inline">\(827\left(0.4704\right)\left(0.37\right) \approx 143.94\)</span></td>
</tr>
<tr class="odd">
<td>Do not know</td>
<td><span class="math inline">\(827\left(0.5296\right)\left(0.2842\right) \approx 124.47\)</span></td>
<td><span class="math inline">\(827\left(0.4704\right)\left(0.2842\right) \approx 110.56\)</span></td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>From here, we’re ready to compute the <span class="math inline">\(\chi^2\)</span> test statistic. We’ll use the original observed data from the table at the beginning of the problem statement, and we’ll use the expected values that we just computed.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>observed <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">154</span>, <span class="dv">132</span>, <span class="dv">180</span>, <span class="dv">126</span>, <span class="dv">104</span>, <span class="dv">131</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>expected <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">151.45</span>, <span class="fl">134.52</span>, <span class="fl">162.05</span>, <span class="fl">143.94</span>, <span class="fl">124.47</span>, <span class="fl">110.56</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>test_stat <span class="ot">&lt;-</span> <span class="fu">sum</span>((observed <span class="sc">-</span> expected)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>expected)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>test_stat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11.45972</code></pre>
</div>
</div>
<blockquote class="blockquote">
<ul>
<li><strong>Compute the <span class="math inline">\(p\)</span>-value:</strong> We’ll now convert our test statistic (a boundary value) into a <span class="math inline">\(p\)</span>-value. Notice from our picture of the alternative hypothesis that our <span class="math inline">\(p\)</span>-value will be the area to the right of the test statistic. Additionally, remember that we’re working with the <span class="math inline">\(\chi^2\)</span> distribution and not the normal distribution here – we’ll use <code>pchisq()</code> rather than <code>pnorm()</code>. The <span class="math inline">\(\chi^2\)</span> distribution is determined by a number of degrees of freedom, not a mean or standard deviation – for this particular type of test (<em>test for independence</em>) – the degrees of freedom is <span class="math inline">\(df = \left(k - 1\right)\left(\ell - 1\right)\)</span>, where <span class="math inline">\(k\)</span> is the number of levels of the first categorical variable (education level) and <span class="math inline">\(\ell\)</span> is the number of levels of the second categorical variable (stance on drilling). Here, we’ll use a <span class="math inline">\(\chi^2\)</span> distribution with <span class="math inline">\(\left(2 - 1\right)\left(3 - 1\right) = 2\)</span> degrees of freedom.</li>
</ul>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>p_val <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(test_stat, <span class="at">df =</span> (<span class="dv">2</span> <span class="sc">-</span> <span class="dv">1</span>)<span class="sc">*</span>(<span class="dv">3</span> <span class="sc">-</span> <span class="dv">1</span>))</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>p_val</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.003247537</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PracticeInferenceProblems_Complete_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<ul>
<li><strong>Compare the <span class="math inline">\(p\)</span>-value to the Level of Significance:</strong> The <span class="math inline">\(p\)</span>-value for our test is around 0.0032. This means that, if the null hypothesis is true, the probability of observing a sample at least as favorable to the alternative hypothesis as ours is around 0.32%. This is quite unlikely!</li>
</ul>
<p>Our <span class="math inline">\(p\)</span> value falls below the level of significance, so our sample is one of those “unlikely” samples which are favorable to the alternative hypothesis. That is, our sample is <em>incompatible</em> with a world in which the null hypothesis is true – we <strong>do</strong> have significant evidence to suggest that the education level and stance on drilling are dependent (associated). <span class="math inline">\(_\blacktriangledown\)</span></p>
</blockquote>
</section>
</section>
<section id="inference-on-one-and-two-means" class="level2">
<h2 class="anchored" data-anchor-id="inference-on-one-and-two-means">Inference on One and Two Means</h2>
<section id="problem-1-solved-2" class="level3">
<h3 class="anchored" data-anchor-id="problem-1-solved-2">Problem 1 Solved</h3>
<p><strong>Problem 1 (Sleep Habits of New Yorkers):</strong> New York is known as “the city that never sleeps”. A random sample of 25 New Yorkers were asked how much sleep they get per night. Statistical summaries of these data are shown below. The point estimate suggests New Yorkers sleep less than 8 hours a night on average. Is the result statistically significant?</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><span class="math inline">\(n\)</span></th>
<th><span class="math inline">\(\bar{x}\)</span></th>
<th><span class="math inline">\(s\)</span></th>
<th><span class="math inline">\(\text{min}\)</span></th>
<th><span class="math inline">\(\text{max}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>25</td>
<td>7.73</td>
<td>0.77</td>
<td>6.17</td>
<td>9.78</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><em>Solution.</em> We’re being asked to conduct a hypothesis test here. Let’s let <span class="math inline">\(\mu\)</span> denote the population mean hours of sleep per night for New Yorkers. This test is to determine whether <span class="math inline">\(\mu\)</span> is less than 8 hours.</p>
<p><strong>Hypotheses:</strong> The hypotheses for this test are <span class="math inline">\(\left\{\begin{array}{lr} H_0: &amp; \mu = 8\\ H_A: &amp; \mu &lt; 8\end{array}\right.\)</span></p>
<p><strong>Picture of Alternative Hypothesis:</strong> Now that we’ve got our hypotheses written out, lets draw a picture of our alternative hypothesis. As a reminder, what we are really drawing is a representation of the samples which would lead us to prefer the alternative hypothesis (<span class="math inline">\(H_a\)</span>) as a description of reality over the null hypothesis (<span class="math inline">\(H_0\)</span>).</p>
</blockquote>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PracticeInferenceProblems_Complete_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Set <span class="math inline">\(\alpha\)</span> Level:</strong> As a reminder, since no level of significance is explicitly requested in the problem statement, we’ll use <span class="math inline">\(\alpha = 0.05\)</span>. This means that, in the image above, the blue shaded area represents a total of 5% of observed samples under the null hypothesis. These are the samples which are “unlikely” enough, under the null hypothesis, that we would reject that null hypothesis and accept the alternative hypothesis instead.</p>
<p><strong>Compute the Test Statistic:</strong> Our job now, is to determine whether our sample is one of those unlikely samples – we’ll do this by identifying a test statistic which represents our sample, and then by computing a corresponding <span class="math inline">\(p\)</span>-value. As a reminder, our test statistic takes the form: <span class="math display">\[\text{test statistic} = \frac{\left(\text{point estimate}\right) - \left(\text{null value}\right)}{\text{standard error}}\]</span></p>
<ul>
<li><p>We can identify our <span class="math inline">\(\text{null value}\)</span> from the <em>null hypothesis</em> (<span class="math inline">\(H_0\)</span>).</p>
<ul>
<li>In looking at that hypothesis, we see that our null value is <span class="math inline">\(8\)</span>.</li>
</ul></li>
<li><p>Our <em>point estimate</em> is the sample mean average hours slept per night, <span class="math inline">\(\bar{x} = 7.73\)</span></p></li>
<li><p>To identify our <em>standard error</em>, we’ll need to walk through the standard error decision tree in order to identify the formula for computing this value.</p>
<ul>
<li>Since we are conducting a hypothesis test on a single population mean, where the population standard deviation is unknown, we land in a box which suggests that <span class="math inline">\(\displaystyle{S_E = \frac{s}{\sqrt{n}}}\)</span> and where we have <em>degrees of freedom</em> equal to one less than the sample size.</li>
<li>Our standard error is then <span class="math inline">\(\displaystyle{\frac{0.77}{\sqrt{25}} = 0.154}\)</span>.</li>
<li>Additionally, the knowledge of <em>degrees of freedom</em> indicates that we can’t use the normal distribution here – instead, we’ll be utilizing a <span class="math inline">\(t\)</span>-distribution with 24 degrees of freedom.</li>
</ul></li>
</ul>
<p>Let’s compute our test statistic:</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>point_est <span class="ot">&lt;-</span> <span class="fl">7.73</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>null_val <span class="ot">&lt;-</span> <span class="dv">8</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">25</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>se <span class="ot">&lt;-</span> <span class="fl">0.77</span><span class="sc">/</span><span class="fu">sqrt</span>(n)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>test_stat <span class="ot">&lt;-</span> (point_est <span class="sc">-</span> null_val)<span class="sc">/</span>se</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>test_stat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.753247</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Convert to <span class="math inline">\(p\)</span>-value:</strong> Now that we have our test statistic, we are ready to compute our <span class="math inline">\(p\)</span>-value. The plot on the left shows our distribution with our test statistic plotted on it. The plot on the right shows the <em>tail area</em> associated with our test statistic.</p>
</blockquote>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PracticeInferenceProblems_Complete_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>That left tail area is our <span class="math inline">\(p\)</span>-value. We’ll compute it below.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>p_val <span class="ot">&lt;-</span> <span class="fu">pt</span>(<span class="sc">-</span><span class="fl">1.75</span>, <span class="at">df =</span> <span class="dv">24</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>p_val</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.04644754</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PracticeInferenceProblems_Complete_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Compare the <span class="math inline">\(p\)</span>-value to the Level of Significance:</strong> The <span class="math inline">\(p\)</span>-value for our test is around <span class="math inline">\(0.0464\)</span>, which is below our level of significance (<span class="math inline">\(\alpha\)</span>). This means that, if the null hypothesis were true, there only about a 4.64% probability of observing a sample at least as favorable to the null hypothesis as our sample data. This is <em>unlikely</em> (according to the <span class="math inline">\(\alpha\)</span> threshold we are using)!</p>
<p>Our <span class="math inline">\(p\)</span>-value falls below our level of significance. This means that our sample <strong>is</strong> one of those samples which is favorable for the alternative hypothesis (<span class="math inline">\(H_a\)</span>). That is, our sample is <em>incompatible</em> with a world in which the null hypothesis is true – we reject the null hypothesis and accept the alternative to it. We <strong>do</strong> have significant evidence to suggest that New Yorkers sleep, on average, less than 8 hours a night. <span class="math inline">\(_\blacktriangledown\)</span></p>
</blockquote>
</section>
<section id="problem-2-solved-2" class="level3">
<h3 class="anchored" data-anchor-id="problem-2-solved-2">Problem 2 Solved</h3>
<p><strong>Problem 2 (Diamond Pricing):</strong> Prices of diamonds are determined by what is known as the 4 Cs: cut, clarity, color, and carat weight. The prices of diamonds go up as the carat weight increases, but the increase is not smooth. For example, the difference between the size of a 0.99 carat diamond and a 1 carat diamond is undetectable to the naked human eye, but the price of a 1 carat diamond tends to be much higher than the price of a 0.99 diamond. In this question we use two random samples of diamonds, 0.99 carats and 1 carat, each sample of size 23, and compare the average prices of the diamonds. In order to be able to compare equivalent units, we first divide the price for each diamond by 100 times its weight in carats. That is, for a 0.99 carat diamond, we divide the price by 99. For a 1 carat diamond, we divide the price by 100. The distributions and some sample statistics are shown below.</p>
<p>Conduct a hypothesis test to evaluate if there is a difference between the average standardized prices of 0.99 and 1 carat diamonds. Make sure to state your hypotheses clearly, check relevant conditions, and interpret your results in context of the data.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>0.99 carats</th>
<th>1 carat</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean</td>
<td>$44.51</td>
<td>$56.81</td>
</tr>
<tr class="even">
<td>SD</td>
<td>$13.32</td>
<td>$16.13</td>
</tr>
<tr class="odd">
<td>n</td>
<td>23</td>
<td>23</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><em>Solution.</em> The goal of this particular research question is to determine whether there is a <em>difference</em> in average price per point (1/100th of a carat) for 0.99 carat diamonds versus full 1.00 carat diamonds. We’ll conduct a hypothesis test for a difference between two population <em>means</em> here.</p>
<blockquote class="blockquote">
<p><em>Note.</em> Each “participant” in this study is a diamond, and the question being asked about each diamond is “what is the price per point that the diamond sells at?”. The answer to this question will be a dollar value, which we then aggregate/summarize using a <em>mean</em> (average). This is the reason that our hypothesis test involves means.</p>
</blockquote>
<p>Knowing that we are conducting a hypothesis test to compare two population means, we are ready to write down our hypotheses for this test. Recall that we are testing for a <em>difference</em> in average per-point prices. The following are our hypotheses for this test:</p>
<p><strong>Hypotheses:</strong> The hypotheses for this test are <span class="math inline">\(\left\{\begin{array}{lr} H_0: &amp; \mu_{0.99} = \mu_{1.00}\\ H_A: &amp; \mu_{0.99} \neq \mu_{1.00}\end{array}\right.\)</span></p>
<p>Notice that this way of writing our hypotheses hides what our <em>null value</em> is and it also hides how we should compute our <em>point estimate</em>. We can rewrite our hypotheses as follows to show these things more explicitly.</p>
<blockquote class="blockquote">
<p><strong>Alternative Phrasing of Hypotheses:</strong> <span class="math inline">\(\left\{\begin{array}{lr} H_0: &amp; \mu_{1.00} - \mu_{0.99} = 0\\ H_A: &amp; \mu_{1.00} - \mu_{0.99} \neq 0\end{array}\right.\)</span></p>
<p>Note that we’ve just “subtracted <span class="math inline">\(\mu_{0.99}\)</span> from both sides” in each hypothesis to change our initial hypotheses into these.</p>
<blockquote class="blockquote">
<p><em>About this choice.</em> We could have chosen to subtract <span class="math inline">\(\mu_{1.00}\)</span> from both sides instead but, intuitively, this would lead to a “negative difference” since we might expect 0.99 carat diamonds to have a lower price per point than full 1.00 carat diamonds. Avoiding negative numbers is sometimes advantageous, but never necessary.</p>
</blockquote>
</blockquote>
<p><strong>Picture of Alternative Hypothesis:</strong> Now that we’ve got our hypotheses written out, lets draw a picture of our alternative hypothesis. As a reminder, what we are really drawing is a representation of the samples which would lead us to prefer the alternative hypothesis (<span class="math inline">\(H_a\)</span>) as a description of reality over the null hypothesis (<span class="math inline">\(H_0\)</span>).</p>
</blockquote>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PracticeInferenceProblems_Complete_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Set <span class="math inline">\(\alpha\)</span> Level:</strong> As a reminder, since no level of significance is explicitly requested in the problem statement, we’ll use <span class="math inline">\(\alpha = 0.05\)</span>. This means that, in the image above, those blue shaded areas represent a total of 5% of observed samples under the null hypothesis. There are 2.5% of samples in each shaded tail – these are the samples which are “unlikely” enough, under the null hypothesis that we would reject that null hypothesis and accept the alternative hypothesis instead.</p>
<p><strong>Compute the Test Statistic:</strong> Our job now, is to determine whether our sample is one of those unlikely samples – we’ll do this by identifying a test statistic which represents our sample, and then by computing a corresponding <span class="math inline">\(p\)</span>-value. As a reminder, our test statistic takes the form: <span class="math display">\[\text{test statistic} = \frac{\left(\text{point estimate}\right) - \left(\text{null value}\right)}{\text{standard error}}\]</span></p>
<ul>
<li><p>We can identify our <span class="math inline">\(\text{null value}\)</span> from the <em>null hypothesis</em> (<span class="math inline">\(H_0\)</span>).</p>
<ul>
<li>In looking at that hypothesis, we see that our null value is <span class="math inline">\(0\)</span>.</li>
</ul></li>
<li><p>We can identify our <em>point estimate</em> by looking at the left-hand side of our null hypothesis and computing the “sample version” of that value.</p>
<ul>
<li>We’ll compute <span class="math inline">\(\bar{x}_{1.00} - \bar{x}_{0.99}\)</span>, the difference in sample mean price-per-point values.</li>
<li>Our <em>point estimate</em> is <span class="math inline">\(56.81 - 44.51\)</span>.</li>
</ul></li>
<li><p>To identify our <em>standard error</em>, we’ll need to walk through the standard error decision tree in order to identify the formula for computing this value.</p>
<ul>
<li>Since we are conducting a hypothesis test to compare two means, where the population standard deviation is unknown, and our data are not paired, we land in a box which suggests that <span class="math inline">\(\displaystyle{S_E = \sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}}}\)</span> and where we have <em>degrees of freedom</em> equal to the minimum between the group sizes minus <span class="math inline">\(1\)</span>.</li>
<li>Our standard error is then <span class="math inline">\(\displaystyle{\sqrt{\frac{\left(13.32\right)^2}{23} + \frac{\left(16.13\right)^2}{23}}}\)</span>.</li>
<li>Additionally, the knowledge of <em>degrees of freedom</em> indicates that we can’t use the normal distribution here – instead, we’ll be utilizing a <span class="math inline">\(t\)</span>-distribution with 22 degrees of freedom.</li>
</ul></li>
</ul>
<p>Let’s compute our test statistic:</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>point_est <span class="ot">&lt;-</span> <span class="fl">56.81</span> <span class="sc">-</span> <span class="fl">44.51</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>null_val <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>sd1 <span class="ot">&lt;-</span> <span class="fl">13.32</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>n1 <span class="ot">&lt;-</span> <span class="dv">23</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>sd2 <span class="ot">&lt;-</span> <span class="fl">16.13</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>n2 <span class="ot">&lt;-</span> <span class="dv">23</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>se <span class="ot">&lt;-</span> <span class="fu">sqrt</span>((sd1<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>n1 <span class="sc">+</span> (sd2<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>n2)</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>test_stat <span class="ot">&lt;-</span> (point_est <span class="sc">-</span> null_val)<span class="sc">/</span>se</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>test_stat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.819881</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Now that we have our test statistic, we are ready to start computing our <span class="math inline">\(p\)</span>-value. The plot on the left shows our distribution with our test statistic plotted on it. The plot on the right shows the <em>tail area</em> associated with our test statistic.</p>
</blockquote>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PracticeInferenceProblems_Complete_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>In order to convert that tail area in the right-most image above into a <span class="math inline">\(p\)</span>-value, we’ll need to double it. We do this because, in our picture of our null hypothesis we have shaded two tail areas there. We’ll compute the <span class="math inline">\(p\)</span>-value below and then plot the results.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>p_val <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">*</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(<span class="fl">2.82</span>, <span class="at">df =</span> <span class="dv">22</span>))</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>p_val</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.009971732</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PracticeInferenceProblems_Complete_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Compare the <span class="math inline">\(p\)</span>-value to the Level of Significance:</strong> The <span class="math inline">\(p\)</span>-value for our test is around <span class="math inline">\(0.01\)</span>, which is below our level of significance (<span class="math inline">\(\alpha\)</span>). This means that, if the null hypothesis were true, there only about a 1% probability of observing a sample at least as favorable to the null hypothesis as our sample data. This is very <em>unlikely</em>!</p>
<p>Our <span class="math inline">\(p\)</span>-value falls below our level of significance. This means that our sample <strong>is</strong> one of those samples which is favorable for the alternative hypothesis (<span class="math inline">\(H_a\)</span>). That is, our sample in <em>incompatible</em> with a world in which the null hypothesis is true – we reject the null hypothesis and accept the alternative to it. We <strong>do</strong> have significant evidence to suggest that the average per-point-price for 0.99 carat diamonds and full 1.00 carat diamonds is different. <span class="math inline">\(_\blacktriangledown\)</span></p>
<blockquote class="blockquote">
<p><strong><em>Ramifications of this Problem:</em></strong> This problem utilizes real data. Should you find yourself in a scenario where you are in the market to purchase a diamond, then you should talk to your partner (or other recipient) about the possibility of looking at diamonds just below major thresholds – for example, a 0.24 carat diamond versus a quarter-carat diamond, a 0.49 carat diamond instead of a half-carat diamond, etc. This can save you significant money. For example, in the case of a 0.99 carat diamond versus a full-carat diamond, the average savings is over $1,250. This is a lot of money – especially when the human eye cannot tell the difference between a 0.99 carat and full 1.00 carat diamond. If owning a home is a goal, then that saved money can be put towards your first house!</p>
</blockquote>
</blockquote>
</section>
<section id="problem-3-unsolved-1" class="level3">
<h3 class="anchored" data-anchor-id="problem-3-unsolved-1">Problem 3 Unsolved</h3>
<p><strong>Problem 3 (Fuel Efficiency of Cars):</strong> The table provides summary statistics on highway fuel economy of 52 cars. Use these statistics to calculate a 98% confidence interval for the difference between average highway mileage of manual and automatic cars, and interpret this interval in the context of the data.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Automatic Highway mpg</th>
<th>Manual Highway mpg</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean</td>
<td>22.92</td>
<td>27.88</td>
</tr>
<tr class="even">
<td>SD</td>
<td>5.29</td>
<td>5.01</td>
</tr>
<tr class="odd">
<td>n</td>
<td>26</td>
<td>26</td>
</tr>
</tbody>
</table>
</section>
<section id="problem-4-unsolved-1" class="level3">
<h3 class="anchored" data-anchor-id="problem-4-unsolved-1">Problem 4 Unsolved</h3>
<p><strong>Problem 4 (Forest Management):</strong> Forest rangers wanted to better understand the rate of growth for younger trees in the park. They took measurements of a random sample of 50 young trees in 2009 and again measured those same trees in 2019. The data below summarize their measurements, where the heights are in feet:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>2009</th>
<th>2019</th>
<th>Differences</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\bar{x}\)</span></td>
<td>12.0</td>
<td>24.5</td>
<td>12.5</td>
</tr>
<tr class="even">
<td>s</td>
<td>3.5</td>
<td>9.5</td>
<td>7.2</td>
</tr>
<tr class="odd">
<td>n</td>
<td>50</td>
<td>50</td>
<td>50</td>
</tr>
</tbody>
</table>
<p>Construct a 99% confidence interval for the average growth of (what had been) younger trees in the park over 2009-2019.</p>
</section>
</section>
<section id="sample-size-problems" class="level2">
<h2 class="anchored" data-anchor-id="sample-size-problems">Sample Size Problems</h2>
<p>The following problems ask us to estimate a required sample size. As a reminder, when estimating sample sizes, we need to round <em>up</em> to the next whole number to ensure that the resulting sample size is large enough to achieve our desired level of confidence and our desired margin of error.</p>
<section id="problem-1-solved-3" class="level3">
<h3 class="anchored" data-anchor-id="problem-1-solved-3">Problem 1 Solved</h3>
<p><strong>Problem 1 (Legalization of Marijuana):</strong> As discussed in Exercise 6.10, the General Social Survey reported a sample where about 61% of US residents thought marijuana should be made legal. If we wanted to limit the margin of error of a 95% confidence interval to 2%, about how many Americans would we need to survey?</p>
<blockquote class="blockquote">
<p><em>Solution.</em> Notice that this problem is asking us to compute a required <em>sample size</em>. In particular, we want to astimate a required sample size for capturing a population <em>proportion</em>. Because of this, we’ll utilize the formula <span class="math inline">\(\displaystyle{n \geq \left(\frac{z_{\alpha/2}}{\text{Margin of Error}}\right)^2\cdot p\left(1 - p\right)}\)</span>. Note that this formula can be found in the top-left of the Standard Error Decision Tree document.</p>
<p>In the formula above, <span class="math inline">\(z_{\alpha/2}\)</span> is the critical value associated with the level of confidence we desire to have in our confidence interval. We can see that <span class="math inline">\(z_{\alpha/2} \approx 1.96\)</span> in this scenario since we desire a 95% confidence interval. Next, we can identify that our <span class="math inline">\(\text{Margin of Error}\)</span> is <span class="math inline">\(0.02\)</span> since we’d like to estimate the proportion of Americans in favor of legalizing marijuana to <em>within 2%</em>. Finally, we can use <span class="math inline">\(p = 0.61\)</span> as an estimate for the true population proportion, since the result cited from the General Social Survey suggests that population proportion (<strong>Note.</strong> If we do not have a prior estimate for the proportion, we should utilize <span class="math inline">\(p = 0.5\)</span>, which is a worst-case scenario, resulting in the largest sample size estimate possible).</p>
<p>Since we have all of the components of the sample size formula, we can now evaluate our sample size.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>z <span class="ot">=</span> <span class="fl">1.96</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>p <span class="ot">=</span> <span class="fl">0.61</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>me <span class="ot">=</span> <span class="fl">0.02</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> (z<span class="sc">/</span>me)<span class="sc">^</span><span class="dv">2</span><span class="sc">*</span>p<span class="sc">*</span>(<span class="dv">1</span> <span class="sc">-</span> p)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>n</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2284.792</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Notice that we get <span class="math inline">\(n \geq 2284.792\)</span>, so we must sample at least 2,285 individuals in order to have the level of confidence and margin of error we desire. (<strong>Note.</strong> In these sample size problems you can never round down – any rounding must always be upwards in order to maintain your desired confidence level and margin of error.). <span class="math inline">\(_\blacktriangledown\)</span></p>
</blockquote>
</section>
<section id="problem-2-solved-3" class="level3">
<h3 class="anchored" data-anchor-id="problem-2-solved-3">Problem 2 Solved</h3>
<p><strong>Problem 2 (Spring Break Spending):</strong> A marketing research firm wants to estimate the average amount a student spends during the Spring break. They want to determine it to within $120 with 90% confidence. The first does some research which allows it to roughly say that Spring Break expenditure ranges from $100 to $1700 per student. They use the approximation <span class="math inline">\(\displaystyle{\frac{\text{range}}{4}}\)</span> for <span class="math inline">\(\sigma\)</span>. How many students should they sample?</p>
<blockquote class="blockquote">
<p><em>Solution.</em> This problem is also asking us to compute a required <em>sample size</em>. In this case, however, we want to astimate a required sample size for capturing a population <em>mean</em>. Because of this, we’ll utilize our other sample size formula, <span class="math inline">\(\displaystyle{n \geq \left(\frac{z_{\alpha/2}\cdot \sigma}{\text{Margin of Error}}\right)^2}\)</span>. Note that this formula can be found in the top-right of the Standard Error Decision Tree document.</p>
<p>Again, <span class="math inline">\(z_{\alpha/2}\)</span> is the critical value associated with the level of confidence we desire to have in our confidence interval. We can see that <span class="math inline">\(z_{\alpha/2} \approx 1.65\)</span> in this scenario since we desire a 90% confidence interval (<strong>Note.</strong> This formula results in a <em>crude approximation</em> of the required sample size, since we are utilizing the normal distribution to obtain <span class="math inline">\(z_{\alpha/2}\)</span>, which may not be warranted – there are software packages that can help us obtain more justifiable estimates). Next, we can identify that our <span class="math inline">\(\text{Margin of Error}\)</span> is $120 since we’d like to estimate the population mean (average) per-student expenditure on Spring Break to within this amount. Finally, we are given some direction on how to estimate the population standard deviation. We can use <span class="math inline">\(\displaystyle{\sigma \approx \frac{\text{range}}{4}}\)</span> (which is a relatively common approximation), so that <span class="math inline">\(\displaystyle{\sigma \approx \frac{1700 - 100}{4} = 400}\)</span>.</p>
<p>Since we have all of the components of the sample size formula, we can now evaluate our sample size.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>z <span class="ot">=</span> <span class="fl">1.65</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">=</span> <span class="dv">400</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>me <span class="ot">=</span> <span class="dv">120</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> (z<span class="sc">*</span>sigma<span class="sc">/</span>me)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>n</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 30.25</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Notice that we get <span class="math inline">\(n \geq 30.25\)</span>, so we must sample at least 31 individuals in order to have the level of confidence and margin of error we desire. As noted in the solution to the previous problem, we must round <em>up</em> in order to maintain our level of confidence and desired margin of error. <span class="math inline">\(_\blacktriangledown\)</span></p>
</blockquote>
</section>
</section>
<section id="comparing-many-means-with-analysis-of-variance-anova" class="level2">
<h2 class="anchored" data-anchor-id="comparing-many-means-with-analysis-of-variance-anova">Comparing Many Means with Analysis of Variance (ANOVA)</h2>
<p>In this section, we explore the use of Analysis of Variance to compare multiple (more than two) group means.</p>
<section id="problem-1-solved-4" class="level3">
<h3 class="anchored" data-anchor-id="problem-1-solved-4">Problem 1 Solved</h3>
<p><strong>Problem 1 (Taylor Swift Songs):</strong> Take a look at the Taylor Albums data frame from the <code>{taylor}</code> R package. Compare one of the song metrics (<code>duration</code>, <code>danceability</code>, <code>speechiness</code>, <code>loudness</code>, etc.) across Taylor’s released albums.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(taylor)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>taylors_version <span class="ot">&lt;-</span> taylor_album_songs <span class="sc">%&gt;%</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_detect</span>(album_name, <span class="st">"Taylor's Version"</span>))</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>taylors_version <span class="sc">%&gt;%</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>lyrics) <span class="sc">%&gt;%</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>() <span class="sc">%&gt;%</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"hover"</span>, <span class="st">"striped"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">album_name</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">ep</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">album_release</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">track_number</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">track_name</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">artist</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">featuring</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">bonus_track</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">promotional_release</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">single_release</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">track_release</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">danceability</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">energy</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">key</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">loudness</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mode</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">speechiness</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">acousticness</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">instrumentalness</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">liveness</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">valence</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">tempo</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">time_signature</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">duration_ms</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">explicit</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">key_name</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">mode_name</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">key_mode</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Fearless (Taylor's Version)</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">2021-04-09</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Fearless (Taylor's Version)</td>
<td style="text-align: left;">Taylor Swift</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">2021-04-09</td>
<td style="text-align: right;">0.569</td>
<td style="text-align: right;">0.741</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">-4.963</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.0282</td>
<td style="text-align: right;">0.0122</td>
<td style="text-align: right;">0e+00</td>
<td style="text-align: right;">0.3330</td>
<td style="text-align: right;">0.430</td>
<td style="text-align: right;">100.118</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">241592</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">F</td>
<td style="text-align: left;">major</td>
<td style="text-align: left;">F major</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fearless (Taylor's Version)</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">2021-04-09</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Fifteen (Taylor's Version)</td>
<td style="text-align: left;">Taylor Swift</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">2021-04-09</td>
<td style="text-align: right;">0.559</td>
<td style="text-align: right;">0.646</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">-4.610</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.0272</td>
<td style="text-align: right;">0.1160</td>
<td style="text-align: right;">0e+00</td>
<td style="text-align: right;">0.3200</td>
<td style="text-align: right;">0.289</td>
<td style="text-align: right;">95.466</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">294419</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">G</td>
<td style="text-align: left;">major</td>
<td style="text-align: left;">G major</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fearless (Taylor's Version)</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">2021-04-09</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Love Story (Taylor's Version)</td>
<td style="text-align: left;">Taylor Swift</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">2021-02-12</td>
<td style="text-align: left;">2021-02-12</td>
<td style="text-align: right;">0.627</td>
<td style="text-align: right;">0.792</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">-4.311</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.0310</td>
<td style="text-align: right;">0.1300</td>
<td style="text-align: right;">4e-06</td>
<td style="text-align: right;">0.0845</td>
<td style="text-align: right;">0.415</td>
<td style="text-align: right;">119.054</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">235767</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">D</td>
<td style="text-align: left;">major</td>
<td style="text-align: left;">D major</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fearless (Taylor's Version)</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">2021-04-09</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">Hey Stephen (Taylor's Version)</td>
<td style="text-align: left;">Taylor Swift</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">2021-04-09</td>
<td style="text-align: right;">0.788</td>
<td style="text-align: right;">0.571</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">-6.135</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.0296</td>
<td style="text-align: right;">0.1060</td>
<td style="text-align: right;">0e+00</td>
<td style="text-align: right;">0.0934</td>
<td style="text-align: right;">0.797</td>
<td style="text-align: right;">115.990</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">254255</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">F#</td>
<td style="text-align: left;">major</td>
<td style="text-align: left;">F# major</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fearless (Taylor's Version)</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">2021-04-09</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">White Horse (Taylor's Version)</td>
<td style="text-align: left;">Taylor Swift</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">2021-04-09</td>
<td style="text-align: right;">0.423</td>
<td style="text-align: right;">0.517</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">-7.377</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.0486</td>
<td style="text-align: right;">0.3690</td>
<td style="text-align: right;">0e+00</td>
<td style="text-align: right;">0.1770</td>
<td style="text-align: right;">0.366</td>
<td style="text-align: right;">185.262</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">234516</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">C</td>
<td style="text-align: left;">major</td>
<td style="text-align: left;">C major</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fearless (Taylor's Version)</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">2021-04-09</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">You Belong With Me (Taylor's Version)</td>
<td style="text-align: left;">Taylor Swift</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">2021-04-09</td>
<td style="text-align: right;">0.632</td>
<td style="text-align: right;">0.773</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">-4.856</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.0346</td>
<td style="text-align: right;">0.0623</td>
<td style="text-align: right;">0e+00</td>
<td style="text-align: right;">0.0885</td>
<td style="text-align: right;">0.474</td>
<td style="text-align: right;">130.033</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">231124</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: left;">F#</td>
<td style="text-align: left;">major</td>
<td style="text-align: left;">F# major</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>taylors_version <span class="sc">%&gt;%</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(album_name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  album_name                       n
  &lt;chr&gt;                        &lt;int&gt;
1 1989 (Taylor's Version)         23
2 Fearless (Taylor's Version)     26
3 Red (Taylor's Version)          30
4 Speak Now (Taylor's Version)    22</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>taylor_anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(danceability <span class="sc">~</span> album_name, <span class="at">data =</span> taylors_version)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(taylor_anova)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq  Mean Sq F value Pr(&gt;F)  
album_name   3 0.0814 0.027146     3.2 0.0268 *
Residuals   96 0.8143 0.008482                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
1 observation deleted due to missingness</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>taylors_version <span class="sc">%&gt;%</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> danceability, <span class="at">fill =</span> album_name, <span class="at">y =</span> album_name)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PracticeInferenceProblems_Complete_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">TukeyHSD</span>(taylor_anova))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PracticeInferenceProblems_Complete_files/figure-html/unnamed-chunk-36-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(taylor_anova)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = danceability ~ album_name, data = taylors_version)

$album_name
                                                                 diff
Fearless (Taylor's Version)-1989 (Taylor's Version)      -0.075461538
Red (Taylor's Version)-1989 (Taylor's Version)           -0.049533333
Speak Now (Taylor's Version)-1989 (Taylor's Version)     -0.070863636
Red (Taylor's Version)-Fearless (Taylor's Version)        0.025928205
Speak Now (Taylor's Version)-Fearless (Taylor's Version)  0.004597902
Speak Now (Taylor's Version)-Red (Taylor's Version)      -0.021330303
                                                                 lwr
Fearless (Taylor's Version)-1989 (Taylor's Version)      -0.14521683
Red (Taylor's Version)-1989 (Taylor's Version)           -0.11712362
Speak Now (Taylor's Version)-1989 (Taylor's Version)     -0.14346725
Red (Taylor's Version)-Fearless (Taylor's Version)       -0.03859283
Speak Now (Taylor's Version)-Fearless (Taylor's Version) -0.06515739
Speak Now (Taylor's Version)-Red (Taylor's Version)      -0.08892059
                                                                  upr     p adj
Fearless (Taylor's Version)-1989 (Taylor's Version)      -0.005706242 0.0286276
Red (Taylor's Version)-1989 (Taylor's Version)            0.018056953 0.2281796
Speak Now (Taylor's Version)-1989 (Taylor's Version)      0.001739978 0.0584160
Red (Taylor's Version)-Fearless (Taylor's Version)        0.090449236 0.7200913
Speak Now (Taylor's Version)-Fearless (Taylor's Version)  0.074353198 0.9981683
Speak Now (Taylor's Version)-Red (Taylor's Version)       0.046259984 0.8424368</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>taylor_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(duration_ms <span class="sc">~</span> danceability <span class="sc">+</span> energy <span class="sc">+</span> loudness <span class="sc">+</span> mode <span class="sc">+</span> speechiness <span class="sc">+</span> liveness <span class="sc">+</span> valence <span class="sc">+</span> tempo, <span class="at">data =</span> taylors_version)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(taylor_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = duration_ms ~ danceability + energy + loudness + 
    mode + speechiness + liveness + valence + tempo, data = taylors_version)

Residuals:
    Min      1Q  Median      3Q     Max 
-103357  -23013   -2686   17721  349021 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   526048.66   73709.38   7.137 2.25e-10 ***
danceability  -84552.70   68043.12  -1.243  0.21720    
energy       -167360.13   54894.75  -3.049  0.00301 ** 
loudness        8954.95    3693.76   2.424  0.01731 *  
mode          -14739.16   26034.18  -0.566  0.57269    
speechiness  -217096.86  261117.68  -0.831  0.40792    
liveness      -47577.30   69585.17  -0.684  0.49588    
valence       -47931.39   34175.11  -1.403  0.16416    
tempo            -87.33     191.97  -0.455  0.65027    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 49650 on 91 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.2612,    Adjusted R-squared:  0.1962 
F-statistic: 4.021 on 8 and 91 DF,  p-value: 0.0004006</code></pre>
</div>
</div>
</section>
<section id="problem-2-solved-4" class="level3">
<h3 class="anchored" data-anchor-id="problem-2-solved-4">Problem 2 Solved</h3>
<p><strong>Problem 2 (Penguin Physiology):</strong> Take a look at the <code>penguins</code> data frame from the <code>{palmerpenguins}</code> R package. Compare one of the body measurements (<code>body_mass_g</code>, <code>flipper_length_mm</code>, <code>bill_depth_mm</code>, etc.) across the different penguin species, islands, or observation years.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'palmerpenguins'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:datasets':

    penguins, penguins_raw</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">%&gt;%</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>() <span class="sc">%&gt;%</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"hover"</span>, <span class="st">"striped"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">species</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">island</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">bill_length_mm</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">bill_depth_mm</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">flipper_length_mm</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">body_mass_g</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">sex</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">year</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">Torgersen</td>
<td style="text-align: right;">39.1</td>
<td style="text-align: right;">18.7</td>
<td style="text-align: right;">181</td>
<td style="text-align: right;">3750</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">2007</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">Torgersen</td>
<td style="text-align: right;">39.5</td>
<td style="text-align: right;">17.4</td>
<td style="text-align: right;">186</td>
<td style="text-align: right;">3800</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">2007</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">Torgersen</td>
<td style="text-align: right;">40.3</td>
<td style="text-align: right;">18.0</td>
<td style="text-align: right;">195</td>
<td style="text-align: right;">3250</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">2007</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">Torgersen</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">2007</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">Torgersen</td>
<td style="text-align: right;">36.7</td>
<td style="text-align: right;">19.3</td>
<td style="text-align: right;">193</td>
<td style="text-align: right;">3450</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">2007</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">Torgersen</td>
<td style="text-align: right;">39.3</td>
<td style="text-align: right;">20.6</td>
<td style="text-align: right;">190</td>
<td style="text-align: right;">3650</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">2007</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">%&gt;%</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(species)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  species       n
  &lt;fct&gt;     &lt;int&gt;
1 Adelie      152
2 Chinstrap    68
3 Gentoo      124</code></pre>
</div>
</div>
<p><strong>Question:</strong> Does average flipper length vary across the three species of penguin? Use <span class="math inline">\(\alpha = 0.10\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>flipper_lengths <span class="ot">&lt;-</span> penguins<span class="sc">$</span>flipper_length_mm</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>species <span class="ot">&lt;-</span> penguins<span class="sc">$</span>species</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>penguin_anova_results <span class="ot">&lt;-</span> <span class="fu">aov</span>(flipper_lengths <span class="sc">~</span> species)</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(penguin_anova_results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)    
species       2  52473   26237   594.8 &lt;2e-16 ***
Residuals   339  14953      44                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
2 observations deleted due to missingness</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(penguin_anova_results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = flipper_lengths ~ species)

$species
                      diff       lwr       upr p adj
Chinstrap-Adelie  5.869887  3.586583  8.153191     0
Gentoo-Adelie    27.233349 25.334376 29.132323     0
Gentoo-Chinstrap 21.363462 19.000841 23.726084     0</code></pre>
</div>
</div>
<p><strong>Question:</strong> Does average bill depth vary across the three species of penguin? Use <span class="math inline">\(\alpha = 0.10\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>penguin_anova_results <span class="ot">&lt;-</span> <span class="fu">aov</span>(bill_depth_mm <span class="sc">~</span> species, <span class="at">data =</span> penguins)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(penguin_anova_results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)    
species       2  904.0   452.0   359.8 &lt;2e-16 ***
Residuals   339  425.9     1.3                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
2 observations deleted due to missingness</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(penguin_anova_results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = bill_depth_mm ~ species, data = penguins)

$species
                        diff        lwr        upr     p adj
Chinstrap-Adelie  0.07423062 -0.3110995  0.4595607 0.8928875
Gentoo-Adelie    -3.36424379 -3.6847143 -3.0437733 0.0000000
Gentoo-Chinstrap -3.43847441 -3.8371903 -3.0397586 0.0000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">TukeyHSD</span>(penguin_anova_results))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PracticeInferenceProblems_Complete_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">%&gt;%</span> </span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">x =</span> bill_depth_mm, <span class="at">fill =</span> species)) <span class="sc">+</span> </span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>species, <span class="at">ncol =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite outside the scale range
(`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PracticeInferenceProblems_Complete_files/figure-html/unnamed-chunk-40-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Question:</strong> Does average bill length vary across the three species of penguin? Use <span class="math inline">\(\alpha = 0.10\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>penguin_anova_results <span class="ot">&lt;-</span> <span class="fu">aov</span>(bill_length_mm <span class="sc">~</span> species, <span class="at">data =</span> penguins)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(penguin_anova_results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)    
species       2   7194    3597   410.6 &lt;2e-16 ***
Residuals   339   2970       9                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
2 observations deleted due to missingness</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(penguin_anova_results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = bill_length_mm ~ species, data = penguins)

$species
                      diff       lwr        upr     p adj
Chinstrap-Adelie 10.042433  9.024859 11.0600064 0.0000000
Gentoo-Adelie     8.713487  7.867194  9.5597807 0.0000000
Gentoo-Chinstrap -1.328945 -2.381868 -0.2760231 0.0088993</code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">TukeyHSD</span>(penguin_anova_results))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PracticeInferenceProblems_Complete_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">%&gt;%</span> </span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">x =</span> bill_length_mm, <span class="at">fill =</span> species)) <span class="sc">+</span> </span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>species, <span class="at">ncol =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite outside the scale range
(`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PracticeInferenceProblems_Complete_files/figure-html/unnamed-chunk-41-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Question:</strong> Are <code>species</code> and <code>island</code> independent? Use <span class="math inline">\(\alpha = 0.05\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>chi_sq_results <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(penguins<span class="sc">$</span>species, penguins<span class="sc">$</span>island, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>chi_sq_results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  penguins$species and penguins$island
X-squared = 299.55, df = 4, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>Penguins Regression:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>mass_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(body_mass_g <span class="sc">~</span> flipper_length_mm <span class="sc">+</span> year, <span class="at">data =</span> penguins)</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mass_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = body_mass_g ~ flipper_length_mm + year, data = penguins)

Residuals:
     Min       1Q   Median       3Q      Max 
-1052.54  -265.45   -23.57   243.70  1196.65 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       208300.559  51980.840   4.007 7.56e-05 ***
flipper_length_mm     50.738      1.506  33.695  &lt; 2e-16 ***
year                -106.718     25.912  -4.119 4.80e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 385.3 on 339 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.7705,    Adjusted R-squared:  0.7691 
F-statistic:   569 on 2 and 339 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="problem-3-unsolved-2" class="level3">
<h3 class="anchored" data-anchor-id="problem-3-unsolved-2">Problem 3 Unsolved</h3>
<p><strong>Problem 3 (NFL Rush Yards by Direction):</strong> Explore the <code>rush_21</code> data frame, containing data on running plays from the 2021 NFL season. Conduct a test to determine whether the average yards gained on a rushing play is associated with the direction (<em>left</em>, <em>middle</em>, <em>right</em>) of the running play.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nflfastR)</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>pbp_21 <span class="ot">&lt;-</span> <span class="fu">load_pbp</span>(<span class="dv">2021</span>)</span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>rush_21 <span class="ot">&lt;-</span> pbp_21 <span class="sc">%&gt;%</span></span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(play_type <span class="sc">==</span> <span class="st">"run"</span>)</span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-8"><a href="#cb78-8" aria-hidden="true" tabindex="-1"></a>rush_21 <span class="sc">%&gt;%</span></span>
<span id="cb78-9"><a href="#cb78-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(rusher, down, qtr, rushing_yards, run_location) <span class="sc">%&gt;%</span></span>
<span id="cb78-10"><a href="#cb78-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>() <span class="sc">%&gt;%</span></span>
<span id="cb78-11"><a href="#cb78-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>() <span class="sc">%&gt;%</span></span>
<span id="cb78-12"><a href="#cb78-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"hover"</span>, <span class="st">"striped"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-hover table-striped caption-top table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">rusher</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">down</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">qtr</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">rushing_yards</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">run_location</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">D.Henry</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-3</td>
<td style="text-align: left;">left</td>
</tr>
<tr class="even">
<td style="text-align: left;">K.Murray</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">right</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C.Edmonds</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">middle</td>
</tr>
<tr class="even">
<td style="text-align: left;">D.Henry</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-1</td>
<td style="text-align: left;">middle</td>
</tr>
<tr class="odd">
<td style="text-align: left;">D.Henry</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">left</td>
</tr>
<tr class="even">
<td style="text-align: left;">D.Henry</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">left</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>